-- MySQL Script generated by MySQL Workbench
-- Fri Apr 11 12:43:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ejemplo_seguridad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ejemplo_seguridad
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `ejemplo_seguridad` ;
-- USE `ejemplo_seguridad` ;

-- -----------------------------------------------------
-- Table `artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artista` (
  `ID_Artista` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `Genero_Musical` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  PRIMARY KEY (`ID_Artista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(50) CHARACTER SET 'utf8mb3' NOT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8mb3' NOT NULL,
  `contrasena` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `activo` TINYINT(1) NULL DEFAULT '1',
  `creado_el` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado_el` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `nombre_usuario` (`nombre_usuario` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auditoria` (
  `id_auditoria` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL DEFAULT NULL,
  `accion` VARCHAR(50) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `tabla_afectada` VARCHAR(50) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `registro_afectado` INT NULL DEFAULT NULL,
  `descripcion` TEXT CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `realizado_el` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_auditoria`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `auditoria_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuarios` (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `programa_concierto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `programa_concierto` (
  `ID_programa` INT NOT NULL AUTO_INCREMENT,
  `Numeros_concierto` INT NOT NULL,
  PRIMARY KEY (`ID_programa`))
ENGINE = InnoDB
AUTO_INCREMENT = 2;


-- -----------------------------------------------------
-- Table `concierto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concierto` (
  `ID_Concierto` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NOT NULL,
  `Entradas_vacias` INT NOT NULL,
  `Programa_Concierto_ID_programa` INT NOT NULL,
  `Artista_ID_Artista` INT NOT NULL,
  PRIMARY KEY (`ID_Concierto`, `Programa_Concierto_ID_programa`, `Artista_ID_Artista`),
  INDEX `fk_concierto_Programa_Concierto1_idx` (`Programa_Concierto_ID_programa` ASC) VISIBLE,
  INDEX `fk_concierto_Artista1_idx` (`Artista_ID_Artista` ASC) VISIBLE,
  CONSTRAINT `fk_concierto_Artista1`
    FOREIGN KEY (`Artista_ID_Artista`)
    REFERENCES `artista` (`ID_Artista`),
  CONSTRAINT `fk_concierto_Programa_Concierto1`
    FOREIGN KEY (`Programa_Concierto_ID_programa`)
    REFERENCES `programa_concierto` (`ID_programa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escala_tecnica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escala_tecnica` (
  `ID_Escala` INT NOT NULL AUTO_INCREMENT,
  `NombreEscalaTecnica` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  PRIMARY KEY (`ID_Escala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `local` (
  `ID_Local` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `Ciudad` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `Pais` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  `Direccion` VARCHAR(100) CHARACTER SET 'utf8mb3' NOT NULL,
  `Telefono` VARCHAR(45) CHARACTER SET 'utf8mb3' NOT NULL,
  PRIMARY KEY (`ID_Local`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `permisos` (
  `id_permiso` INT NOT NULL AUTO_INCREMENT,
  `nombre_permiso` VARCHAR(50) CHARACTER SET 'utf8mb3' NOT NULL,
  `descripcion` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `creado_el` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado_el` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_permiso`),
  UNIQUE INDEX `nombre_permiso` (`nombre_permiso` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `realizacion_escala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `realizacion_escala` (
  `ID_Realizacion` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATETIME NULL DEFAULT NULL,
  `Escala_Tecnica_ID_Escala` INT NOT NULL,
  `Local_ID_Local` INT NOT NULL,
  `Programa_Concierto_ID_programa` INT NOT NULL,
  PRIMARY KEY (`ID_Realizacion`, `Escala_Tecnica_ID_Escala`, `Local_ID_Local`, `Programa_Concierto_ID_programa`),
  INDEX `fk_Realizacion_Escala_Escala_Tecnica_idx` (`Escala_Tecnica_ID_Escala` ASC) VISIBLE,
  INDEX `fk_Realizacion_Escala_Local1_idx` (`Local_ID_Local` ASC) VISIBLE,
  INDEX `fk_Realizacion_Escala_Programa_Concierto1_idx` (`Programa_Concierto_ID_programa` ASC) VISIBLE,
  CONSTRAINT `fk_Realizacion_Escala_Escala_Tecnica`
    FOREIGN KEY (`Escala_Tecnica_ID_Escala`)
    REFERENCES `escala_tecnica` (`ID_Escala`),
  CONSTRAINT `fk_Realizacion_Escala_Local1`
    FOREIGN KEY (`Local_ID_Local`)
    REFERENCES `local` (`ID_Local`),
  CONSTRAINT `fk_Realizacion_Escala_Programa_Concierto1`
    FOREIGN KEY (`Programa_Concierto_ID_programa`)
    REFERENCES `programa_concierto` (`ID_programa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(50) CHARACTER SET 'utf8mb3' NOT NULL,
  `descripcion` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `creado_el` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `actualizado_el` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `nombre_rol` (`nombre_rol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rol_permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rol_permiso` (
  `id_rol` INT NOT NULL,
  `id_permiso` INT NOT NULL,
  `asignado_el` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_rol`, `id_permiso`),
  INDEX `id_permiso` (`id_permiso` ASC) VISIBLE,
  CONSTRAINT `rol_permiso_ibfk_1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `roles` (`id_rol`),
  CONSTRAINT `rol_permiso_ibfk_2`
    FOREIGN KEY (`id_permiso`)
    REFERENCES `permisos` (`id_permiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sesiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sesiones` (
  `id_sesion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL DEFAULT NULL,
  `token` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL,
  `ip_address` VARCHAR(45) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `inicio` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fin` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id_sesion`),
  UNIQUE INDEX `token` (`token` ASC) VISIBLE,
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `sesiones_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuarios` (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario_rol` (
  `id_usuario` INT NOT NULL,
  `id_rol` INT NOT NULL,
  `asignado_el` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`, `id_rol`),
  INDEX `id_rol` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `usuario_rol_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `usuarios` (`id_usuario`),
  CONSTRAINT `usuario_rol_ibfk_2`
    FOREIGN KEY (`id_rol`)
    REFERENCES `roles` (`id_rol`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
